# Generated by Django 3.0.3 on 2020-02-25 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Category')),
                ('imgpath', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('logo', models.CharField(max_length=100, verbose_name='logo')),
                ('contacts', models.CharField(choices=[(996709202111, 'Phone'), ('www.facebook.com', 'Facebook'), ('course@gmail.com', 'Email')], default=996709202111, max_length=50)),
                ('branches', models.CharField(choices=[(42.8667, 'Latitude'), (74.566742, 'Longitude'), ('70 ул. Байтик баатыра, Бишкек', 'Address')], default='70 ул. Байтик баатыра, Бишкек', max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Category', verbose_name='Category')),
            ],
        ),
    ]
