# Generated by Django 3.0.3 on 2020-02-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.CharField(choices=[(42.8667, 'Latitude'), (74.566742, 'Longitude'), ('Бишкек, Байтик баатыра 70', 'Address')], default='Бишкек, Байтик баатыра 70', max_length=300),
        ),
    ]
