# Generated by Django 3.0.3 on 2020-03-04 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_auto_20200227_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={},
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='branches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_app.Branch', verbose_name='branches'),
        ),
    ]
