# Generated by Django 3.0.3 on 2020-03-09 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_auto_20200309_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='course_app.Course'),
        ),
    ]
